site_name: Ongaku Docs
site_url: https://ongaku.mplaty.com/
repo_url: https://github.com/MPlatypus/hikari-ongaku/

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
          options:
            heading_level: 3
            annotations_path: source
            docstring_section_style: spacy
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            extensions:
                - griffe_inherited_docstrings


markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2023 MPlaty

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MPlatypus/hikari-ongaku
      name: Hikari Ongaku Github

nav:
  - home: index.md
  - Getting Started:
    - getting_started/index.md
    - Basics: getting_started/basics.md
    - Filters: getting_started/filters.md
    - Nodes: getting_started/nodes.md
  - API Reference:
    - api_reference/index.md
    - Ongaku: api_reference/ongaku.md
    - Node: api_reference/node.md
    - Player: api_reference/player.md
    - Rest: api_reference/rest.md
    - Enums: api_reference/enums.md
    - Errors: api_reference/errors.md
    - ABC:
      - Base: api_reference/abc/base.md
      - Events: api_reference/abc/events.md
      - Lavalink: api_reference/abc/lavalink.md
      - Player: api_reference/abc/player.md
      - Session: api_reference/abc/session.md
      - Track: api_reference/abc/track.md
      - Filters: api_reference/abc/filters.md


watch:
  - docs
  - ongaku
