site_name: Ongaku Docs

site_url: https://ongaku.mplaty.com/

repo_url: https://github.com/MPlatypus/hikari-ongaku/


theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Quicksand
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.png


extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
          options:
            heading_level: 3
            annotations_path: source
            docstring_section_style: spacy
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            extensions:
                - griffe_inherited_docstrings


markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html


copyright: Copyright &copy; 2023 MPlaty

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MPlatypus/hikari-ongaku
      name: Hikari Ongaku Github


nav:
  - home: index.md
  - Getting Started:
    - getting_started/index.md
    - Basics: getting_started/basics.md
    - Filters: getting_started/filters.md
    - Sessions: getting_started/sessions.md
    - Plugins: getting_started/plugins.md
  - API Reference:
    - api/index.md
    - Client: api/client.md
    - Session: api/session.md
    - Player: api/player.md
    - Rest: api/rest.md
    - Enums: api/enums.md
    - Errors: api/errors.md
    - Handlers: api/handlers.md
    - ABC:
      - Bases: api/abc/bases.md
      - Error: api/abc/error.md
      - Events: api/abc/events.md
      - Filters: api/abc/filters.md
      - Info: api/abc/info.md
      - Player: api/abc/player.md
      - Playlist: api/abc/playlist.md
      - Route Planner: api/abc/route_planner.md
      - Session: api/abc/session.md
      - Statistics: api/abc/statistics.md
      - Track: api/abc/track.md
  - Extensions:
    - ext/index.md
    - Creation: ext/creation.md
    - Checker: ext/checker.md
  - Changelog: changelog.md


watch:
  - docs
  - ongaku
