site_name: Ongaku Docs
site_url: https://ongaku.mplaty.com/

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            merge_init_into_class: true
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            annotations_path: source
            docstring_section_style: spacy


markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2023 MPlaty

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MPlatypus/hikari-ongaku
      name: Hikari Ongaku Github

nav:
  - home: index.md
  - Getting Started:
    - getting_started/index.md
    - Basics: getting_started/basics.md
    - Commands: getting_started/commands.md
    - Nodes: getting_started/nodes.md
  - API Reference:
    - api_reference/index.md
    - Ongaku: api_reference/ongaku.md
    - Player: api_reference/player.md
    - Rest: api_reference/rest.md
    - Events:
      - Track: api_reference/events/track.md
      - Other: api_reference/events/other.md
    - ABC:
      - Events: api_reference/abc/events.md
      - Lavalink: api_reference/abc/lavalink.md
      - Player: api_reference/abc/player.md
      - Session: api_reference/abc/session.md
      - Track: api_reference/abc/track.md
    - errors: api_reference/errors.md

watch:
  - docs
  - ongaku
