site_name: hikari ongaku documentation

theme:
  name: material
  palette:
    scheme: slate
    primary: purple
    accent: black
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest

plugins:
  - search

nav:
  - home: index.md
  - Getting Started:
    - getting_started/index.md
    - hikari: getting_started/hikari.md
    - lightbulb: getting_started/lightbulb.md
    - tanjun: getting_started/tanjun.md
    - akarui: getting_started/akarui.md
  - API Reference:
    - api_reference/index.md
    - Ongaku: api_reference/ongaku.md
