name: CodeClimate Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codeclimate-test-reporter

      - name: Run tests
        run: |
          python -m unittest discover ./tests

      - name: Upload coverage report to CodeClimate
        run: |
          codeclimate-test-reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_ID }}
