name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: |
          pip install build
          python -m build
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}